### ISSUE TITLE
Does training in 2k make a significant difference?

### ISSUE THREAD

**Issue by pablodawson** [oppo-us-research/SpacetimeGaussians#34]
Hey, thanks for your great work. I noticed you hard-coded a "imageW" and "imageH" value, which it is not actually used afterwards, so the image used is of the original resolution.
https://github.com/oppo-us-research/SpacetimeGaussians/blob/72d92222453b590d4eedf9b09504e971d42768fc/thirdparty/gaussian_splatting/scene/dataset_readers.py#L110
I managed to train Neu3D with significantly less (8gb) RAM by resizing the image to that size. Does that make a big difference in your experiments?
Thanks.

**Comment by lizhan17** [comment]
we haven't try it. because previous methods work on half resolution. But I think 2K resolution will producer a sharper visual. 

- n3d is trained with half resoluton.
- technicolor is original resolution. you can change these two dataset with the arguement. "resolution"
- immersive distorted is a specialy case, which we resize the ground truth image directly in the loader[code](https://github.com/oppo-us-research/SpacetimeGaussians/blob/72d92222453b590d4eedf9b09504e971d42768fc/thirdparty/gaussian_splatting/utils/camera_utils.py#L141) to compensate for the resampling error. Our method render at the original resolution. But the ground truth image for training is half resolution, which is same with other methods. 

you can chage resolution by ```resolution``` from 2 to 4 in Neu3D, which means only 25% resolution. this is implemented by 3dgs. please ignore imageH.

**Comment by pablodawson** [comment]
Got it, thanks! In case you're curious quality seems to be pretty similar.
![00000](https://github.com/oppo-us-research/SpacetimeGaussians/assets/74978011/512306fb-9c47-4d0d-9663-d305760baa7e)
